#!/bin/zsh
if [ $2 ]
then
    echo $1 >> $2
else
    echo "Using default doi list name and filepath"
    # echo $1 >> doi_list.txt
    echo $1 >> doi-list.txt
fi

if [ $3 ]
then
    doi2bib $1 >> $3
else
    echo "Using default bibliography name and filepath"
    # doi2bib $1 >> bibliography.bib
    doi2bib $1 >> bibliography.bib
fi
